name: 'eipw'
description: 'Run eipw, the EIP validator, as a GitHub action'
inputs:
  token:
    description: 'GitHub Secret Token'
    required: true
  include:
    description: 'Newline separated list of globs to watch for changed files'
    required: false
    default: 'EIPS/**'
  working-directory:
    description: 'Path where the repository is checked out'
    required: false
    default: ''
  unchecked:
    description: 'EIP numbers (comma separated) that should not be linted'
    required: false
    default: ''
  deny-checks:
    description: 'Replace these checks with errors'
    required: false
    default: ''
  warn-checks:
    description: 'Replace these checks with warnings'
    required: false
    default: ''
  allow-checks:
    description: 'Hide these checks'
    required: false
    default: ''
  options-file:
    description: 'Path to TOML configuration file'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
