name: 'eipw'
description: 'Run eipw, the EIP validator, as a GitHub action'
inputs:
  token:
    description: 'GitHub Secret Token'
    required: true
  unchecked:
    description: 'EIP numbers (comma separated) that should not be linted'
    required: false
    default: ''
  warn-checks:
    description: 'Replace these checks with warnings'
    required: false
    default: ''
  info-checks:
    description: 'Replace these checks with info'
    required: false
    default: ''
  hide-checks:
    description: 'Hide these checks'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
