on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 22

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Commit & Push changes
        uses: actions-js/push@5f565701a8b9f9aa6b7efc25f28994eabfcf5312
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update dist/index.js; ${{ github.event.head_commit.message }}
          branch: dist
          force: true
